---
  - name: create jobs directory for {{ jenkins_job_name }}
    file:
      path: "{{ jenkins_job_path}}"
      state: directory
      owner: jenkins
      group: jenkins

  - name: create workplace directory for {{ jenkins_job_name }}
    file:
        path: "{{ jenkins_workspace_path }}"
        state: directory
        owner: jenkins
        group: jenkins

  - name: upload files - source repos
    copy:
      src: files/{{ item }}.txt
      dest: "{{ jenkins_workspace_path }}{{ item }}.txt"
      owner: jenkins
      group: jenkins
      mode: 0644
    with_items:
      - src_repos
      - pages_repos

  - name: upload script
    copy:
      src: files/{{ item }}.sh
      dest: "{{ jenkins_workspace_path }}{{ item }}.sh"
      owner: jenkins
      group: jenkins
      mode: 0755
    with_items:
      - update_repo

  - name: set up {{ jenkins_job_name }} config file
    template:
      src: templates/jobs/{{ jenkins_job_name }}/config.j2
      dest: "{{ jenkins_job_path }}config.xml"
      owner: jenkins
      group: jenkins
      mode: 0644

  - name: restart jenkins
    service:
      name: jenkins
      state: restarted